### PR TITLE
Fix code-related issues from PED (Russell)

### LINKED ISSUE #297: [PE-D][Tester D] Unable to add module using lower case prefix
Users are not allowed to add modules using lower-case letters as prefix, even if it is a valid NUS module. The error message provided only states that the prefix should be 2-3 letters long, but no information is provided about it being restricted to upper case letters only (this applies to the UG as well). 

This could be inconvenient for the user who has to switch to caps to insert the module tag.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: huixuant/ped#6

### LINKED ISSUE #307: [PE-D][Tester A] `delete 0` does not provide a response in Command Response box
## Step to reproduce 
1. Run `delete 0`

## Expected 
Perhaps inform user that their own data cannot be deleted (or anything, up to your own discretion)

## Actual 
No feedback is given to user regarding `delete 0`

## Screenshot
Calling `delete 0` results in no change 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ShanHng/ped#7

### LINKED ISSUE #316: [PE-D][Tester C] Misleading error message for entering "@@" in telegram handle
Error message states that should not be blank and should start with @ symbol but the tele handle that I added fulfils both those requirements. Perhaps you can have a different error message for errors that are not the two above cases.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cyiting/ped#11

### PR DESCRIPTION
**Pull request by russelltankaimin**
## Ready for review

- [x] Telegram Handle error message (#316)
- [x] `delete 0` response fix (#307)
- [x] Fix unable to add module using lower case prefix (#297)

Fixes #316 
Fixes #307 
Fixes #297

### CODE REVIEW

File: src/main/java/seedu/address/model/tag/ModuleTag.java [hunk 1]
```diff
@@ -50,7 +50,7 @@ public ModuleTag(String moduleCode, Lesson... lessons) {
      * Overloaded constructor for a {@code ModuleTag}
      */
     public ModuleTag(String moduleCode, Collection<Lesson> lessons) {
-        super(moduleCode);
+        super(moduleCode.toUpperCase());
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/model/tag/ModuleTag.java:53]: Fixes #297

File: src/main/java/seedu/address/model/tag/ModuleTag.java [hunk 2]
```diff
@@ -41,7 +41,7 @@ public ModuleTag(String tagName) {
      * Overloaded constructor for a {@code ModuleTag}
      */
     public ModuleTag(String moduleCode, Lesson... lessons) {
-        super(moduleCode);
+        super(moduleCode.toUpperCase());
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/model/tag/ModuleTag.java:44]: Fixes #297

File: src/main/java/seedu/address/model/tag/ModuleTag.java [hunk 3]
```diff
@@ -21,7 +21,7 @@ public class ModuleTag extends Tag implements Comparable<ModuleTag> {
 
     public static final String MESSAGE_CONSTRAINTS =
             "NUS Modules should have 2 - 3 letter prefix, followed by 4 digits and optional 1 - 3 alphabets";
-    public static final String VALIDATION_REGEX = "[A-Z]{2,4}[0-9]{4}[A-Z]{0,3}";
+    public static final String VALIDATION_REGEX = "[a-zA-Z]{2,4}[0-9]{4}[a-zA-Z]{0,3}";
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/model/tag/ModuleTag.java:24]: This is an alternative way of solving it, though I think they achieve the same thing. I'd prefer the latter version to fix #297.

File: src/main/java/seedu/address/model/person/TelegramHandle.java [hunk 4]
```diff
@@ -10,7 +10,8 @@
 public class TelegramHandle implements Comparable<TelegramHandle> {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Telegram Handle should not be blank and should start with @ symbol";
+            "Telegram Handle should be at least 5 characters long start with @ symbol"
+        + "\nAdditionally, it can contain any combination of letters, numbers and underscores only";
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/model/person/TelegramHandle.java:14]: Is this enforced? I don't see the restriction of 5 characters anywhere.

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 5]
```diff
@@ -35,6 +38,11 @@ public DeleteCommand(ContactIndex contactIndex) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+
+        if (contactIndex.equals(USER_CONTACT_INDEX)) {
+            throw new CommandException(MESSAGE_CANNOT_DELETE_OWN_PROFILE);
+        }
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java:44]: Hmm alright, so in this case, a contact index of 0 will make it to this stage? LGTM, since this is a defensive programming practice.

**Review by mynameizzhafeez — APPROVED** [review]
LGTM.
