### PR TITLE
Fix duplicate index

### LINKED ISSUE #327: [Bug] Adding Person when list is filtered will result in a duplicate index created.
Steps to recreate:
`sample 100`
`find n/chu` (find the first guy of the list)
`add n/abc`
List will now have two persons with index 2.

### PR DESCRIPTION
**Pull request by kennycjy**
Fixes #327

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -50,10 +50,13 @@ public AddCommand(Person person) {
     public ViewCommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
 
+
         if (model.hasPerson(this.candidatePerson)) {
             throw new CommandException(MESSAGE_DUPLICATE_PERSON);
         }
 
+        model.updateObservablePersonList();
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:58]: Thank you :)

**Review by mynameizzhafeez — APPROVED** [review]
LGTM.
