### PR TITLE
Fix PE-D Bugs

### LINKED ISSUE #250: [Organise Command] Does not check for clash in meet ups
## Reproduce:
Just `organise` on a different location, but same timing or any timing with clashes

## Expected to see
Add meet up failure

## Actual
Meet up created

## Possible soln:
Do a time clash check using `TimeUtils`

### LINKED ISSUE #278: [PE-D][Tester D] User profile not updated
Upon editing the user's own profile, the display on the top left of the UI is not updated to reflect the change. The display is only refreshed when the user exits and reopens the app.

This could confuse the user and leave them wondering if their profile had been edited/updated successfully.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: huixuant/ped#3

### LINKED ISSUE #295: [PE-D][Tester C] Deleted contact appears in Scheduled Meet Up Panel
To reproduce: meet 1 2 3 4 followed by delete 1

Contact with index 1 still shows up in scheduled meet up panel despite being deleted

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cyiting/ped#8

### LINKED ISSUE #319: [PE-D][Tester C] add command suddenly stopped working
I'm not sure how I got it to be like that but I was testing the commands and suddenly the add command stopped working. As shown in the video, I tried all the other commands and they seem to work fine, I could also do "add n/Ritchie Thompson" and it would throw me the correct error, i.e. "This person already exists in the address book" but anytime I tried to add someone new the command isn't accepted and no error message is thrown either.

<i><video controls><source src="https://raw.githubusercontent.com/cyiting/ped/main/files/8cde3528-14cd-426e-8b49-b2d1b744953e.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/cyiting/ped/main/files/8cde3528-14cd-426e-8b49-b2d1b744953e.mp4</i>

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: cyiting/ped#14

### LINKED ISSUE #320: [PE-D][Tester C] Follow up from error 12: Organising with a non-existent contact will result in the meetup being added to the panel
Meetup is added to the panel as shown

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cyiting/ped#15

### LINKED ISSUE #334: Editing Contact Name does not Update in  Scheduled Meet Panel
Editing the name of a person who is in the schedule meet up pane should update the meet up pane.

### LINKED ISSUE #339: Editing Contact does not Update Meet Participants List
e.g meet 1 2 3 -> edit name of contact 1 -> organise 1 -> error: <previous name of contact 1> does not exist in your contacts

### PR DESCRIPTION
**Pull request by zichen-3974**
fix #339 
fix #334 
fix #320
fix #319 
fix #295 
fix #278 
fix #250

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -158,8 +189,44 @@ public Person addPerson(Person person) {
...
+     * @param participantsList List of persons participating in the meet up.
+     * @param target Person to be edited.
+     * @param editedPerson Person with edited details.
+     * @param meetUp The meet up to be updated.
+     */
+    public void updatePersonList(List<Person> participantsList, Person target,
+                                 Person editedPerson, MeetUp meetUp) {
+        if (participantsList.removeIf(person -> person.isSamePerson(target))) {
+            participantsList.add(editedPerson);
+            meetUp.setParticipants(new Participants(participantsList));
```
Comment (seanfirefox) [inline src/main/java/seedu/address/model/ModelManager.java:228]: Be careful of using `removeIf` along with `Iterator` in case of `ConcurrentModificationException`. Although I do not think that there is anything wrong with your code since you are calling them on 2 different lists, just check again to be safe so as not to introduce bugs.

**Review by seanfirefox — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/model/Model.java [hunk 2]
```diff
@@ -209,21 +209,23 @@ public interface Model {
...
     void deleteMeetUp(MeetUpIndex meetUpIndex);
 
     void addMeetUp(MeetUp meetUp);
 
-    boolean hasMeetUp(MeetUp meetUp);
-
     MeetUpIndex getMeetUpIndex();
 
+    void updateObservableMeetUpList();
+    void updateObservableMeetUpList(Comparator<MeetUp> comparator);
```
[the remark this answers is not in the document]
Comment (zichen-3974) [reply src/main/java/seedu/address/model/Model.java:221]: Having a white space here fails check style for me, which is why I removed it.

File: src/main/java/seedu/address/model/meetup/UniqueMeetUpList.java [hunk 3]
```diff
@@ -73,6 +73,19 @@ public void remove(MeetUp toRemove) {
...
+     * Removes meet ups with no more participants.
+     */
+    public void removeEmptyMeetUps() {
+        Iterator<MeetUp> iterator = internalList.iterator();
+        while (iterator.hasNext()) {
+            MeetUp meetUp = iterator.next();
+            if (meetUp.getParticipants().getParticipants().isEmpty()) {
+                iterator.remove();
+            }
+        }
```
Comment (russelltankaimin) [inline src/main/java/seedu/address/model/meetup/UniqueMeetUpList.java:86]: Wow. So interesting haha

File: src/main/java/seedu/address/logic/parser/MeetUpIndexHandler.java [hunk 4]
```diff
@@ -26,7 +26,8 @@ public MeetUpIndexHandler(Model model) {
      */
     public MeetUpIndex assignMeetUpIndex() {
         List<MeetUp> meetUpList = model.getObservableMeetUpList();
-        if (meetUpList.isEmpty()) {
+        if (meetUpList.isEmpty() || meetUpList.stream()
+                .noneMatch(meetUp -> meetUp.getMeetUpIndex().equals(new MeetUpIndex(1)))) {
```
Comment (russelltankaimin) [inline src/main/java/seedu/address/logic/parser/MeetUpIndexHandler.java:30]: Nice catch

**Review by russelltankaimin — APPROVED** [review]

File: src/main/java/seedu/address/model/ModelManager.java (hunk 1 above)
Comment (zichen-3974) [reply src/main/java/seedu/address/model/ModelManager.java:228]: Hmm I see, I thought `removeIf` helped [prevent](https://www.baeldung.com/java-concurrentmodificationexception) `ConcurrentModificationException` so I used that instead, but using `remove` seems to work fine too so I'll change it.

Comment (russelltankaimin) [reply src/main/java/seedu/address/model/ModelManager.java]: There is still a risk of `ConcurrentModificationException` as you are still modifying a `Collection` while iterating over it. `Iterators` actually help to prevent this. Saying this because I realised `removeIf` is invoked by a `Collection`.

Comment (zichen-3974) [reply src/main/java/seedu/address/model/ModelManager.java]: Mm I see, thanks!

File: src/main/java/seedu/address/model/Model.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (seanfirefox) [reply src/main/java/seedu/address/model/Model.java:221]: Oh, LGTM then!

**Review by seanfirefox — APPROVED** [review]
LGTM!
