### PR TITLE
Fix PE-D Issues Assigned to Hafeez

### LINKED ISSUE #260: [Sort Command] Default Sort does not says how it is sorted by

### LINKED ISSUE #273: [PE-D][Tester C] No limit for the phone number length
to reproduce: edit 9 p/123456789101112131415161718192021222324252627282930

reason: Not reasonable for any country's phone number to be this long. Could possibly restrict its length?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: cyiting/ped#2

### LINKED ISSUE #277: [PE-D][Tester B] Tag isn't wrapped
When inputting a tag that is longer than the width of the box, it does not wrap around the box. Hence, it overflows which creates formatting issues.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cmang12/ped#2

### LINKED ISSUE #299: [PE-D][Tester B] No Error Message Prompted
When I typed this command out, no error message is prompted but I am unable to enter the command. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cmang12/ped#9

### LINKED ISSUE #305: [PE-D][Tester D] Person List UI does not update correctly after adding tag
Adding tags results in indeterministic behaviour of Person List UI. 

For example, after the user issues an add tag command (e.g. `tag 1 g/Cycling`), Person List does not show or reflect the updated tag immediately, only after another command has been executed. 

Furthermore, some added tags are not displayed at all. In the screenshot below, Henry has a module tag for `CS1231S` that is not shown in the Person List. 

The user would typically expect to see all tags that are associated with a person in the Person List. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: huixuant/ped#8

### LINKED ISSUE #306: [PE-D][Tester A] `sample` modifies user details
## Step to reproduce 
1. Edit user data with `edit`
2. Run `sample 100`
3. Run `view` to look at user details / click on the button with user's name inside 

## Expected
User data to persist through calling `sample`

## Actual 
User data is erased and replaced with default. 

## Screenshot
This is after clearing the user data with `edit m/`. 

After running `sample 10`, it stays the same (as profile panel is not updated yet).

Calling `view` or clicking on the button in the left panel shows the sample default user with fields populated

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ShanHng/ped#6

### LINKED ISSUE #309: [PE-D][Tester D] Unable to view module days and times
Users are unable to view the day and time of module tags that they have added. 

This could be inconvenient as users are not allowed to add module tags that have overlapping days/times with an existing module tag as shown.

However, without a feature to view the day and time of existing tagged modules, it would be difficult for the user to find out which tag is causing the clash in commitment. 

It is also possible for the user to mistype the day/time when issuing the tag command. However, this error will stay undetected since there is currently no way of viewing the day and time information of a module within the app. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: huixuant/ped#9

### LINKED ISSUE #317: [PE-D][Tester C] Able to meet contacts even after deletion
To reproduce error: delete 1 followed by meet 1

meet 1 should not be allowed anymore, but yet the command is still accepted and the ui still will display a set of meetup locations and timings for contact 1.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cyiting/ped#12

### LINKED ISSUE #318: [PE-D][Tester C] Able to untag non-existent tags
To reproduce error: view any contact and untag any tag that does not exist such as "g/ASDFGGK"

Command is accepted and command result box displays "Group(s) untagged to Person!"

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cyiting/ped#13

### PR DESCRIPTION
**Pull request by mynameizzhafeez**
Solves
Fixes #317 Able to meet contacts after deletion
Fixes #318 Able to untag non-existent tags
Fixes #299 No error message prompted
Fixes #260 Default sort message
Fixes #309 Unable to view module days and times
Fixes #277 Tag isn't wrapped
Fixes #273 No limit for phone number length
Fixes #305 Person List does not update correctly after adding tag
Fixes #306 `sample` modifies user details

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -44,7 +44,7 @@ public CommandResult execute(Model model) throws CommandException {
 
         Person personToDelete = targetPerson.get();
         model.deletePerson(personToDelete);
-        return new CommandResult(String.format(MESSAGE_DELETE_PERSON_SUCCESS, personToDelete));
+        return new ViewCommandResult(String.format(MESSAGE_DELETE_PERSON_SUCCESS, personToDelete), model.getUser());
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java:47]: Fixes #302

File: src/main/java/seedu/address/logic/commands/MeetCommand.java [hunk 2]
```diff
@@ -59,6 +61,18 @@ public MeetCommand(Set<ContactIndex> indices, Collection<Location> locations) {
...
         requireNonNull(model);
+        IndexHandler indexHandler = new IndexHandler(model);
+        Set<ContactIndex> invalidContactIndices = indices.stream()
+                .filter(i -> indexHandler.getPersonByIndex(i).isEmpty())
+                .collect(Collectors.toSet());
+
+        if (!invalidContactIndices.isEmpty()) {
+            String message = invalidContactIndices.stream()
+                    .map(ContactIndex::toString)
+                    .collect(Collectors.joining(", "));
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/MeetCommand.java:72]: Fixes #317

File: src/main/java/seedu/address/logic/commands/TagCommand.java [hunk 3]
```diff
@@ -109,7 +109,7 @@ private ViewCommandResult tagPersonModules(Model model) throws CommandException
                 new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX));
         Person editedPerson = personToEdit.copy();
 
-        addModuleTags(editedPerson);
+        Set<ModuleTag> addedModuleTags = addModuleTags(editedPerson);
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/TagCommand.java:112]: We return something so that we know what module tags have been added.

File: src/main/java/seedu/address/logic/commands/TagCommand.java [hunk 4]
```diff
@@ -118,7 +118,12 @@ private ViewCommandResult tagPersonModules(Model model) throws CommandException
 
         model.setPerson(personToEdit, editedPerson);
 
-        return new ViewCommandResult(MESSAGE_MODULE_TAG_PERSON_SUCCESS, editedPerson);
+        String message = MESSAGE_MODULE_TAG_PERSON_SUCCESS
+                + addedModuleTags.stream()
+                .map(ModuleTag::toString)
+                .collect(Collectors.joining("\n"));
+
+        return new ViewCommandResult(message, editedPerson);
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/TagCommand.java:126]: We format the `addedModuleTags` to fit within the Command Result.

File: src/main/java/seedu/address/logic/commands/TagCommand.java [hunk 5]
```diff
@@ -131,18 +136,30 @@ private ViewCommandResult tagGroups(Model model) throws CommandException {
...
+        }
 
-        return (personToEdit instanceof User)
-                ? new ViewCommandResult(MESSAGE_GROUP_TAG_USER_SUCCESS, personToEdit)
-                : new ViewCommandResult(MESSAGE_GROUP_TAG_PERSON_SUCCESS, personToEdit);
+        String messageGroupTags = addedGroupTags.stream()
+                .map(GroupTag::toString)
+                .collect(Collectors.joining("\n"));
+
+        return (editedPerson instanceof User)
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/TagCommand.java:153]: Fixes #305

File: src/main/java/seedu/address/logic/commands/TagCommand.java [hunk 6]
```diff
@@ -152,19 +169,28 @@ private ViewCommandResult tagUserModules(Model model) throws CommandException {
...
+        if (TimeUtil.hasAnyClash(timePeriods)) {
+            throw new CommandException("There is a clash in the commitments provided!");
+        }
+
+        if (!editedPerson.canAddCommitments(lessons)) {
+            throw new CommandException(editedPerson.getClashingCommitmentsAsStr(lessons));
         }
 
-        editedPerson.addModuleTags(moduleTags);
+        return editedPerson.addModuleTags(moduleTags);
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/TagCommand.java:193]: We treat these as separate as they should return separate messages.

File: src/main/java/seedu/address/logic/commands/UntagCommand.java [hunk 7]
```diff
@@ -100,7 +101,7 @@ private ViewCommandResult untagPersonModules(Model model) throws CommandExceptio
                 new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX));
         Person editedPerson = personToEdit.copy();
 
-        editedPerson.removeModuleTags(moduleTags);
+        Set<ModuleTag> removedModuleTags = editedPerson.removeModuleTags(moduleTags);
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/commands/UntagCommand.java:104]: Added so we know what have been successfully removed.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 8]
```diff
@@ -262,6 +262,14 @@ public static LocalTime parseLocalTime(String localTimeAsStr, boolean isStartHou
         }
     }
 
+    private static TimeBlock parseTimeBlock(LocalTime startTime, LocalTime endTime, Day day) throws ParseException {
+        if (startTime.isAfter(endTime) || startTime.isEqual(endTime)) {
+            throw new ParseException("Start Time must be STRICTLY BEFORE End Time!");
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:267]: Message copied over.

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java [hunk 9]
```diff
@@ -84,9 +85,14 @@ public SortCommand parse(String args) throws ParseException {
...
-        String comparatorDesc = CollectionUtil
+        List<String> comparatorDescs = CollectionUtil
                 .zip(comparatorNameStream, isAscendingStream, this::getComparatorDesc)
-                .collect(Collectors.joining("\n"));
+                .collect(Collectors.toList());
+
+        Collections.reverse(comparatorDescs);
+        comparatorDescs.add("Index: Ascending");
+
+        String comparatorDesc = String.join("\n", comparatorDescs);
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java:95]: Fix a bug where Sort Command shows the comparators in reverse order.

File: src/main/java/seedu/address/model/ModelManager.java [hunk 10]
```diff
@@ -253,6 +253,7 @@ public void updateObservablePersonList(Predicate<Person> predicate) {
     @Override
     public void updateObservablePersonList() {
         filteredPersons.setPredicate(PREDICATE_SHOW_ALL_PERSONS);
+        observablePersons.setComparator(COMPARATOR_CONTACT_INDEX_PERSON.reversed());
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/model/ModelManager.java:256]: Reverses and unreverses the ordering so that UI components are responsive. Fixes #305

File: src/main/java/seedu/address/model/commitment/Commitment.java [hunk 11]
```diff
@@ -60,6 +63,18 @@ public boolean canFitIntoDaySchedule(ArrayList<HourBlock> slots) {
...
+     */
+    public Set<Commitment> getClashingCommitments(ArrayList<HourBlock> slots) {
+        Set<Commitment> clashingCommitments = new HashSet<>();
+        for (int i = getStartTime().getHourOfDay() - 8; i < getEndTime().getHourOfDay() - 8; i++) {
+            Optional<Commitment> commitment = slots.get(i).getCommitment();
+            commitment.ifPresent(clashingCommitments::add);
+        }
+        return clashingCommitments;
+    }
+
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/model/commitment/Commitment.java:77]: Fixes #299

File: src/main/java/seedu/address/model/person/Person.java [hunk 12]
```diff
@@ -165,22 +168,39 @@ public boolean isSamePerson(Person otherPerson) {
...
-    public void addGroupTags(Set<GroupTag> groupTags) {
-        this.getGroupTags().addAll(groupTags);
+    public Set<GroupTag> addGroupTags(Set<GroupTag> groupTags) {
+        Set<GroupTag> currentGroupTags = getImmutableGroupTags();
+        Set<GroupTag> addableGroupTags = groupTags.stream()
+                .filter(gt -> !currentGroupTags.contains(gt))
+                .collect(Collectors.toSet());
+        this.getGroupTags().addAll(addableGroupTags);
+        return addableGroupTags;
     }
```
Comment (mynameizzhafeez) [inline src/main/java/seedu/address/model/person/Person.java:180]: We now need to know the group tags that have been successfully added.

File: src/main/java/seedu/address/logic/commands/TagCommand.java (hunk 4 above)
Comment (russelltankaimin) [reply src/main/java/seedu/address/logic/commands/TagCommand.java:126]: ok good job

**Review by russelltankaimin — APPROVED** [review]
OK LGTM.
